<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <RootNamespace>Stratus.Projector.Host</RootNamespace>
    <AssemblyName>Stratus.Projector.Host</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Stratus.Projector.Infrastructure/Stratus.Projector.Infrastructure.csproj" />
    <ProjectReference Include="../../../BuildingBlocks/Stratus.ServiceDefaults/Stratus.ServiceDefaults.csproj" />
  </ItemGroup>
</Project>
