<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <RootNamespace>Stratus.Notifier</RootNamespace>
    <AssemblyName>Stratus.Notifier</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../shared/Contracts/Stratus.Contracts.csproj" />
    <ProjectReference Include="../../shared/ServiceDefaults/Stratus.ServiceDefaults.csproj" />
    <ProjectReference Include="../../shared/Messaging/Stratus.Messaging.csproj" />
  </ItemGroup>

</Project>
